/**
 * HomeInsideOut.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpStatusCode } from './httpStatusCode';


export interface BaseResponse { 
    message?: string | null;
    statusCode?: HttpStatusCode;
    readonly hasError?: boolean;
}
export namespace BaseResponse {
}


